### ISSUE TITLE
CPUかGPUをコマンドライン引数で変えられるようにしてはどうでしょう？

### ISSUE THREAD

**Issue by fukatani** [Chizuchizu/bunkasai_face#3]
ユーザーにコードを書き換えてもらうのはあまりよくないので、
(アップデートする時に変更箇所が消えたりしてしまうなど、)
使い方のところにはなるべく、「ここを書き換える」というのは無い方がいいように思います。

Pythonだとargparseというライブラリが有名で、
https://qiita.com/kzkadc/items/e4fc7bc9c003de1eb6d0
に使い方があります。よく使うライブラリなので、覚えておいて損はありません。

main.py --gpuでGPU版で動く、なにもなければCPUというのが例えば考えられます。

**Comment by chizuchizu** [comment]
ありがとうございます。
初耳だったので色々調べて今日中に実装完了させてcommitしようと思います。（行き詰まったり進捗あったりしたらまたリプライします）

**Comment by fukatani** [comment]
悩んだら聞いて貰えれば！

**Comment by chizuchizu** [comment]
![image](https://user-images.githubusercontent.com/44621609/65247764-ef841c00-db2b-11e9-9d20-f32e4dbd5c40.png)
![image](https://user-images.githubusercontent.com/44621609/65247797-fad74780-db2b-11e9-8640-4f40a30ea246.png)

コマンドライン上での実行ができません……（指摘してもらったargparseは関係なく）

実行できないので今はargparseの実験もできないですね

どうしたら動作しますか？

**Comment by fukatani** [comment]
http://harist.hatenablog.jp/entry/2016/03/12/222258
Pycharm上でもコマンドライン引数を使って実行することが出来ます。
まずはこれでやってみてはどうでしょう？

ただimportの方も気になりますね。相対インポート使うという手はありそうです。

あと全然レスポンスの速さは気にしてないので、中学生は早めに寝ましょう笑
githubのイシューなんて、一週間とかそれ以上、無限に放置されるものもありますから。

**Comment by fukatani** [comment]
![test](https://user-images.githubusercontent.com/8858287/65249369-d466db80-db2e-11e9-9420-cf65c232c4bf.png)

**Comment by chizuchizu** [comment]
ありがとうございます。設定して実行してみたら認識されたので今日はもう寝ます。
相対インポート等の実装はまた明日以降、手が空いたらやろうと思います。（近い内にまたリプすると思います）

色々教えてくださってありがとうございます。助かります。

**Comment by chizuchizu** [comment]
mainを一番上の階層に持ってきたら無事動きました。
コマンドライン上でも確認できたのでコマンドライン引数は完成したと思います。

これで大丈夫であればcloseします。他に何かあればアドバイスお願いします。

**Comment by fukatani** [comment]
いいと思います！
細かいこと言うと、parserはメンバ変数じゃなくてもいい気はしました。
ローカル変数はそのスコープでしか影響を及ぼさないので、スコープが広いメンバ変数よりもトラブルは少ないです。

**Comment by chizuchizu** [comment]
確かにそのほうが後々のトラブルが減らせそうですね！ありがとうございます。

修正しました。

**Comment by fukatani** [comment]
:+1:

**Comment by chizuchizu** [comment]
ありがとうございます！
