### ISSUE TITLE
xmlファイルのディレクトリ指定について

### ISSUE THREAD

**Issue by fukatani** [Chizuchizu/bunkasai_face#4]
```python
from Pathlib import Path
self.cascade_file = Path(__file__).parent / "haarcascade_frontalface_alt.xml"
```

みたいな感じで書けば、常にmain.pyと同じディレクトリにあるhaarcascade_frontalface_alt.xmlを指定することが出来ます。多分。

**Comment by chizuchizu** [comment]
ありがとうございます。コードの一部で使ってみました。

xmlファイルを絶対パスで書いたらエラー出たので、相対パスのままにして実行する時にcd ../bunkasai_headcamera を実行してもらうようにしました。

アドバイスがあればお願いします。

**Comment by fukatani** [comment]
コードの編集がなくなったので、前より良くなったと思います！

**Comment by chizuchizu** [comment]
ありがとうございました！
